<?php
$lang = array(
    'cs' => array(
        'menu_about' => 'O programu',
	'menu_run' => 'Spustit',
	'menu_api' => 'REST API',
	'run_about_line' => 'SouDeC je program, webová aplikace a služba REST API pro detekci a klasifikaci citačních zdrojů v českých textech.',
	'run_server_info_word_limit' => 'Upozorňujeme, že vzhledem k časovým limitům našeho proxy serveru je maximální délka vstupního textu přibližně 10 tisíc slov.',
	'run_server_info_label' => 'Server',
	'run_server_info_version' => 'verze',
	'run_server_info_version_unknown' => 'neznámá',
	'run_server_info_status' => 'stav',
	'run_server_info_status_error' => 'server SouDeC je momentálně mimo provoz',
	'run_options_input_label' => 'Vstup',
	'run_options_input_plain' => 'Prostý text',
	'run_options_input_plain_popup' => 'Vstupní formát: prostý text',
	'run_options_input_presegmented' => 'Předrozdělený',
	'run_options_input_presegmented_popup' => 'Předrozdělený vstupní formát (každá věta na samostatném řádku)',
	'run_options_input_conllu' => 'CoNLL-U',
	'run_options_input_conllu_popup' => 'Vstupní text ve formátu CoNLL-U',
	'run_options_output_label' => 'Výstup',
	'run_options_output_conllu' => 'CoNLL-U (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">CoNLL-U+NE+SD</a>)',
	'run_options_output_conllu_popup' => 'CoNLL-U se zdroji a třídami v sloucpi misc',
	'run_options_output_txt' => 'TXT (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">zvýraznění pomocí znaků</a>)',
	'run_options_output_txt_popup' => 'Prostý text se zdroji a třídami označenými pomocí speciálních znaků',
	'run_options_output_html' => 'HTML (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">s barevným zvýrazněním</a>)',
	'run_options_output_html_popup' => 'HTML se zdroji a třídami barevně zvýrazněnými',
	'run_input_text' => 'Vstupní text',
	'run_input_text_default_text' => 'Ministr financí přislíbil, že platy státních zaměstnanců vzrostou o osm procent.',
	'run_input_text_button_delete' => '',
	'run_input_text_button_delete_tooltip' => 'Smazat vstupní text',
	'run_input_file' => 'Vstupní soubor',
	'run_input_file_button_load' => 'Nahrát soubor',
	'run_input_file_kb_loaded_prefix' => 'nahráno ',
	'run_input_file_kb_loaded_suffix' => ' kb',
	'run_process_input' => 'Zpracovat vstup',
	'run_process_input_processing' => 'Probíhá',
	'run_output_ud' => 'UD',
	'run_output_ud_show_trees_tooltip' => 'Zobrazit stromy',
	'run_output_ud_show_conllu_tooltip' => 'Zobrazit CoNLL-U',
	'run_output_ud_save_tree_tooltip' => 'Uložit strom ve formátu SVG',
	'run_output_ud_save_conllu_tooltip' => 'Uložit ve formátu CoNLL-U',
	'run_output_pdtb' => 'PDTB3',
	'run_output_pdtb_show_text_tooltip' => 'Zobrazit text',
	'run_output_pdtb_show_column_tooltip' => 'Zobrazit sloupcový stand-off formát PDTB',
	'run_output_pdtb_save_text_tooltip' => 'Uložit prostý text',
	'run_output_pdtb_save_column_tooltip' => 'Uložit sloupcový stand-off formát PDTB',
	'run_output_text' => 'Výstup',
	'run_output_text_button_save' => 'Uložit',
	'run_output_statistics' => 'Další informace',
	'run_output_statistics_button_save' => 'Uložit',
	'info_basic_label' => 'Základní informace',
	'info_basic_authors' => 'Autoři',
	'info_basic_homepage' => 'Domovská stránka',
	'info_basic_repository' => 'Vývojový repozitář',
	'info_basic_development_status' => 'Stav vývoje',
	'info_basic_development_status_development' => 'vývojová verze',
	'info_basic_OS' => 'OS',
	'info_basic_licence' => 'Licence',
	'info_basic_contact' => 'Kontakt',
	'api_service_url' => 'Rozhraní REST API k webové službě SouDeC je k dispozici na'
    ),

    'en' => array(
        'menu_about' => 'About',
	'menu_run' => 'Run',
	'menu_api' => 'REST API',
	'run_about_line' => 'SouDeC is a tool, a web application and a REST API service for detection and classification of citation sources in Czech.',
	'run_server_info_word_limit' => 'Please note that due to time limitations on our proxy server, the maximum length for input text is approximately 10 thousand words.',
	'run_server_info_label' => 'Server',
	'run_server_info_version' => 'version',
	'run_server_info_version_unknown' => 'unknown',
	'run_server_info_status' => 'status',
	'run_server_info_status_error' => 'the SouDeC server seems to be off-line',
	'run_options_input_label' => 'Input',
	'run_options_input_plain' => 'Plain text',
	'run_options_input_plain_popup' => 'Plain text input format',
	'run_options_input_presegmented' => 'Pre-segmented',
	'run_options_input_presegmented_popup' => 'Pre-segmented input format (sentence per line)',
	'run_options_input_conllu' => 'CoNLL-U',
	'run_options_input_conllu_popup' => 'CoNLL-U input format',
	'run_options_output_label' => 'Output',
	'run_options_output_conllu' => 'CoNLL-U (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">CoNLL-U+NE+SD</a>)',
	'run_options_output_conllu_popup' => 'CoNLL-U with sources and classes in the misc column',
	'run_options_output_txt' => 'TXT (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">marked with characters</a>)',
	'run_options_output_txt_popup' => 'Plain text with sources and classes marked with special characters',
	'run_options_output_html' => 'HTML (<a href="http://ufal.mff.cuni.cz/soudec/users-manual#run_soudec_output" target="_blank">colour-marked</a>)',
	'run_options_output_html_popup' => 'HTML with colour-marked sources and classes',
	'run_input_text' => 'Input Text',
	'run_input_text_button_delete' => '',
	'run_input_text_button_delete_tooltip' => 'Delete the input text',
	'run_input_file' => 'Input File',
	'run_input_file_button_load' => 'Load File',
	'run_input_file_kb_loaded_prefix' => '',
	'run_input_file_kb_loaded_suffix' => 'kb loaded',
	'run_process_input' => 'Process Input',
	'run_process_input_processing' => 'Working',
	'run_output_ud' => 'CoNLL-U',
	'run_output_ud_show_trees_tooltip' => 'Show trees',
	'run_output_ud_show_conllu_tooltip' => 'Show CoNLL-U',
	'run_output_ud_save_conllu_tooltip' => 'Save in the CoNLL-U format',
	'run_output_ud_save_tree_tooltip' => 'Save the tree as SVG',
	'run_output_pdtb' => 'PDTB3',
	'run_output_pdtb_show_text_tooltip' => 'Show the text',
	'run_output_pdtb_show_column_tooltip' => 'Show the PDTB stand-off column format',
	'run_output_pdtb_save_text_tooltip' => 'Save the plain text',
	'run_output_pdtb_save_column_tooltip' => 'Save the PDTB stand-off column format',
	'run_output_text' => 'Output',
	'run_output_text_button_save' => 'Save',
	'run_output_statistics' => 'Further info',
	'run_output_statistics_button_save' => 'Save',
	'info_basic_label' => 'Basic info',
	'info_basic_authors' => 'Authors',
	'info_basic_homepage' => 'Homepage',
	'info_basic_repository' => 'Development repository',
	'info_basic_development_status' => 'Development status',
	'info_basic_development_status_development' => 'development',
	'info_basic_OS' => 'OS',
	'info_basic_licence' => 'Licence',
	'info_basic_contact' => 'Contact',
	'api_service_url' => 'SouDeC REST API web service is available on'
    )
);
?>


